name: Build Electron Apps and Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci

    - name: Build Electron app
      run: npm run build
      env:
        CI: false
        GH_TOKEN: ${{ github.token }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deepseek-desktop-${{ matrix.os }}
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to create releases
    if: github.event_name == 'push' && github.ref_type == 'tag'  # Explicit tag check
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Create/Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Automated release for Deepseek Desktop
          Version: ${{ github.ref_name }}
        files: |
          dist/**/*
        replace: true
